#!/usr/bin/env perl

use Mojolicious::Lite;
use Buzzwords::Indie;
use Text::Markdown 'markdown';

get '/' => sub {
    my $self = shift;
    $self->render;
} => 'index';

get '/about' => sub {
    my $self = shift;
    $self->render;
} => 'about';

websocket '/get_content' => sub {
    my $self = shift;
    $self->on(
        message => sub {
            my $self = shift;
            $self->send( buzzwords() );
        }
    );
};
            

sub buzzwords {
    my $content = Buzzwords::Indie->new();
    return markdown( $content->generate_content());
};

app->start;
