#!/usr/bin/env perl

# See README for information about this application.

use lib 'lib';
use Mojolicious::Lite;
use Buzzwords::Reader;
use Buzzwords::Shuffler;
use Text::Markdown 'markdown';

my %buzzwords = get_buzzwords('indiegaming.buzz');

get '/' => sub {
    my $self = shift;
    $self->render;
} => 'index';

get '/about' => sub {
    my $self = shift;
    $self->render;
} => 'about';

get '/get_content' => sub {
    my $self = shift;

    my $buzzer = Buzzwords::Shuffler->new( buzzwords => \%buzzwords );
    my $content =  markdown( $buzzer->content() );
    $self->render_json(
        {
            html => $content
        }
    );
} => 'get_content';

app->start;
