#!/usr/bin/env perl

# See README for information about this application.

use lib 'lib';
use Mojolicious::Lite;
use Buzzwords::Reader;
use Buzzwords::Shuffler;
use Text::Markdown 'markdown';

get '/' => sub {
    my $self = shift;
    $self->render;
} => 'index';

get '/about' => sub {
    my $self = shift;
    $self->render;
} => 'about';

get '/get_content' => sub {
    my $self = shift;

    my %buzzwords = get_buzzwords('indiegaming.buzz');
    my $buzzer = Buzzwords::Shuffler->new( buzzwords => \%buzzwords );
    my $content =  markdown( $buzzer->content() );
    $self->render_json(
        {
            html => $content
        }
    );
} => 'get_content';
            

helper buzzwords => sub {

    my %buzzwords = get_buzzwords('indiegaming.buzz');
    my $buzzer = Buzzwords::Shuffler->new( buzzwords => \%buzzwords );
    return markdown( $buzzer->content() );

};

app->start;

__DATA__
