#!/usr/bin/env perl

use warnings;
use strict;

use lib 'lib/';

use Buzzwords::Indie;
use Buzzwords::Reader;

my %buzzwords = get_buzzwords('indiegaming.buzz');

my $buzzer = Buzzwords::Indie->new( buzzwords => \%buzzwords );

print $buzzer->generate_content();
